### ISSUE TITLE
Datensatz am Sonntag 05.06.2022

### ISSUE THREAD

**Issue by iceweasel1** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv#20]
Gibt es heute irgendeinen Fehler im System? Sowohl das RKI-Dashobard gibt für die ganze Bundesrepublik 0 neue Fälle in allen Kategorien aus, als auch die der Datensatz hier aus GitHub. Hätte nicht künftig an den Wochenenden die Fallzahlenveröffentlichtung eingestellt sein sollen? Das würde sich mit dem oben genannten, das man dennoch täglich veröffentlicht, aber ohne Aktualisierung darin, widersprechen, bzw. keinen Sinn ergeben. Warum wird dann doch ein Datensatz für z. B. den heutigen Tag veröffentlicht?

Denn die 0 neuen Fälle (Tote, Infizierte, etc.) für die ganze Bundesrepublik, hat bereits Medien heute Meldungen veröffentlichen lassen, sowie bei Twitter spezielle Gruppierungen, die das natürlich riesig feiern/befeuern, das in keinem einzigen Kreis nun ein Fall ist. (Was schlichtweg unwahr ist).

Rund 2.000 neue Infizierte gibt es heute jedoch in ganz Deutschland. (Aus allen 400 Kreisen, die die heute gemeldet haben und die Ministerien, die heute ebenfalls gemeldet habe.). 2.000 ist immer noch ein unterschied als nichts.

**Comment by CharlesStr** [comment]
auch auf dem "Robert Koch-Institut: COVID-19-Dashboard" gab es am 04.06.2022 keine Covid19 Fälle, sowie keine Covid19TodesFälle. Die Datei vom 05.06,2022 war unvollständig. Auch am 05.06.2022 sind keine Covid19Todesfälle aufgezeichent?

**Comment by HannesWuensche** [comment]
Hallo @CharlesStr, 

in den Daten vom 04.06.2022 werden neue Fälle ausgewiesen: 
> [2022-06-04_Deutschland_SarsCov2_Infektionen.csv](https://media.githubusercontent.com/media/robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland/master/Archiv/2022-06-04_Deutschland_SarsCov2_Infektionen.csv)

Wie das ESRI Dashboard diese verarbeitet können wir vom Open Data Team leider nicht sagen, hier müsste ESRI direkt angefragt werden. 

Beste Grüße
@HannesWuensche 
für das Team RKI | OpenData

**Comment by HannesWuensche** [comment]
Hallo @iceweasel1,

vielen Dank für den Hinweis. 
Wir sehen das Problem und versuchen schnellstmöglich Rückmeldung zu geben. 

Beste Grüße
@HannesWuensche 
für das Team RKI | OpenData

**Comment by CharlesStr** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\inter\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\inter\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Hallo @HannesWuensche 
ich arbeite jetzt seit langem mit eueren Daten, und gleiche ab. Bisher 100% alles gut. Aber eben diese Zahlen aus euerern Daten, ergeben keine Sinn. auch die Größe der bereitgestellten TagesDatei ist nicht plausibe. Das Große Problem, die 7TageInzidenz ist dadurch falsch.

Beste Grüße
@CharlesStr

Datenstand | AnzahlFallGesamt | AnzahlFallGesamtTag | TodesfallGesamt | TodesfallGesamtTag
-- | -- | -- | -- | --
05.06.2022 00:00 | 26.493.235 |   | 139.386 |  
06.06.2022   00:00 | 26.496.611 | 3.376 | 139.386 |  
07.06.2022 00:00 | 26.498.361 | 1.750 | 139.388 | 2



</body>

</html>

**Comment by CharlesStr** [comment]
Hier haben wir jetzt auch eine Erklärung der unvollständigen Daten an den Wochehenden. https://www.spiegel.de/wissenschaft/corona-in-deutschland-warum-montags-der-inzidenz-nicht-mehr-zu-trauen-ist-a-a06f41e7-df80-409a-8921-e0f7ed376b87
