### ISSUE TITLE
RKI gibt beim Landkreis Göttingen (NI) 12.314 Infizierte weniger an

### ISSUE THREAD

**Issue by iceweasel1** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv#21]
Hallo Zusammen, 

wie kommt eine so starke Differenz zustande? Sowohl in den Daten, als ebenso im RKI-Dashboard wird der Landkreis Göttingen (NI) mit 79.703 Infizierte (kumuliert) ausgegeben. Das Landratsamt veröffentlicht seit Beginn der Pandemie werktäglich die Fallzahlen. Heute wird dort 92.017 Infizierte (kumuliert) ausgegeben. Das sind 12.314 Infizierte weniger, die das RKI ausgibt. 

Gibt es hierfür eine Erklärung? Die Daten eines Landratsamtes (Gesundheitsamt) sind ja ebenfalls zweifelsfrei verifiziert.
https://www.goettingen.de/portal/meldungen/uebersicht-900000614-25480.html

Beste Grüße

**Comment by HannesWuensche** [comment]
Hallo @iceweasel1,

vielen Dank für die Anfrage und Entschuldigung für die sehr späte Antwort!
Ist die Frage noch aktuell? Falls ja, bitten wir um Rückmeldung in den nächsten zwei Wochen. Dann würden wir versuchen die Frage intern zu klären.

Herzliche Grüße
RKI Open Data Team
