### ISSUE TITLE
Update 2022-12-15 ausgefallen / Archivdatei fehlt

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv#23]
Hi,

gestern ist das Update 2022-12-15 ausgefallen und nun fehlt auch im Archiv die Datei 
2022-12-15_Deutschland_SarsCov2_Infektionen.csv

Viele Grüße
David

**Comment by HannesWuensche** [comment]
Hallo @icestorm972,

vielen Dank für den Hinweis. Aufgrund eines hohen Krankenstands im Teams konnten wir uns leider erst jetzt um das Problem kümmern. Die fehlende Datei ist ergänzt. 

Mit besten Grüßen
@HannesWuensche 
für das Team RKI | Open Data
