### ISSUE TITLE
Wie werden Reinfektionen berücksichtigt?

### ISSUE THREAD

**Issue by lucid-dreams** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv#24]
Wann gelten Reinfektionen [1] als neue Fälle?

Hintergrund der Frage ist die aktuelle Häufung von verstorbenen Genesenen in Berlin.

[1] https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Reinfektion.html

**Comment by RKIOpenData** [comment]
Hallo @lucid-dreams ,

vielen Dank für die Anfrage und Entschuldigung für die sehr späte Antwort!
Ist die Frage noch aktuell? Falls ja, bitten wir um Rückmeldung in den nächsten zwei Wochen. Dann würden wir versuchen die Frage intern zu klären.

Herzliche Grüße
RKI Open Data Team
