### ISSUE TITLE
Raw data missing for 2023-03-13

### ISSUE THREAD

**Issue by LalonSander** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv#26]
The archive is missing data for 2023-03-13: https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv/tree/master/Archiv

This is causing problems for our scripts that calculate 7-day-infection rates etc.

We would be really grateful if the data could be updated as soon as possible!

Lalon Sander/NDR Data

**Comment by arhelgers** [comment]
Thanks for the data. I currently try to implement it. Unfortunately our automated checks show 17 different IdBundesland instead of 16 (+1 NA), which is causing problems regenerating our dataframes. Could you please check, if there is something wrong with the dataset? I have the same issue with the 2023-03-14 and -15 but not with 2023-03-12.

**Comment by HannesWuensche** [comment]
Dear @arhelgers,

could you please specify your observation a bit? 
The dataset only contains the idLandkreis. I have done a short look-up and conld not find any NA for idLandkeis so far. 

Best regrads
@HannesWuensche 
Team RKI | Open Data

**Comment by arhelgers** [comment]
Dear @HannesWuensche,
sorry, I referred to a dataframe generated by us. My bad. Still there are 412 unique idLandkreis-values, for 2023-03-12 there are only 411.

**Comment by HannesWuensche** [comment]
Dear @arhelgers,

I can't find the extra idLandkreis in 2023-03-13. 
Can you tell me whtich one it is? 

Best regrads
@HannesWuensche
Team RKI | Open Data

**Comment by arhelgers** [comment]
Dear @HannesWuensche,
maybe it's also a problem on our side (or even me). After downloading the data from the archive, zipping it for storage and opening it for calculations there are NAs the dataset.
What is troubling me: I recovered data in the exact same way at the beginning of the year and everything worked fine.
