### ISSUE TITLE
Metadaten gelöscht?!

### ISSUE THREAD

**Issue by Rubber1Duck** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv#28]
Warum wurden denn die Metadaten gelöscht?

**Comment by HannesWuensche** [comment]
Hallo @Rubber1Duck, 

da wir mit dem Archiv keine Publikation bei Zenodo vornehmen, 
werden in unserem Prozess auch die Metadaten nicht mehr automatisch aktualisiert. 

Die aktuellsten Metadaten lassen sich im Datensatz [SARS-CoV-2-Infektionen_in_Deutschland)(https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland) abrufen.

Mit besten Grüßen
@HannesWuensche 
für das Team | RKI Open Data
