### ISSUE TITLE
Fehlende Dateien vom 27.10.2023 und 29.10.2023

### ISSUE THREAD

**Issue by dlippold** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv#30]
Im Archiv fehlen die Dateien vom 27.10.2023 und vom 29.10.2023. Da ich für mein Projekt unter https://covid19-de-stats.sourceforge.io/ täglich die aktuelle Datei von https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland/ herunterlade und die beiden genannten Dateien noch nicht gelöscht habe, könnte ich diese zur Verfügung stellen.

**Comment by RKIOpenData** [comment]
Hallo @dlippold,

vielen Dank für den Hinweis und Entschuldigung für die späte Antwort. Wir haben jetzt die fehlenden Archive nachgetragen. Es sollte jetzt alles soweit passen.

beste Grüße
Knut Perseke
für das Team RKI | Open Data
