### ISSUE TITLE
Kein Update seit 2024-01-13

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv#31]
Es fehlen Updates ...

**Comment by RKIOpenData** [comment]
Hallo @jwildeboer,

kannst du nochmal näher beschreiben was dir fehlt? Die Daten der letzten Tage sahen für mich in Ordnung aus auf den ersten Blick.

Best Grüße
Knut Perseke
für das Team | RKI Open Data
