### ISSUE TITLE
Der Datensatz vom 11.02.2024 fehlt

### ISSUE THREAD

**Issue by Rubber1Duck** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv#34]
Der Datensatz vom 11.02.2024 fehlt, obwohl es einen entsprechenden "tag" (täg) gibt!

**Comment by HannesWuensche** [comment]
Hallo @Rubber1Duck,

vielen Dank für den Hinweis. Der Fehler kam zustande, da es zu einem Ausfall am 10.02.2024 kam.  
Wir haben die Daten dem Archiv hinzugefügt. 

Beste Grüße
@HannesWuensche 
für das Team RKI | Open Data
