### ISSUE TITLE
Das Archiv vom 28.05.2024 fehlt

### ISSUE THREAD

**Issue by Rubber1Duck** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv#38]
Kann das noch nachgeliefert werden?

**Comment by Rubber1Duck** [comment]
ja, nein ,vieleicht ? wenigstens eine Antwort wäre toll

**Comment by RKIOpenData** [comment]
Hallo @Rubber1Duck ,

Entschuldigung für die verspätete Antwort. Aufgrund von Krankheiten haben wir leider längere Bearbeitungszeiten als sonst. Wir haben den Datenstand vom 28.5. jetzt noch einmal neu hochgeladen.

viele Grüße
Knut | für das Team RKIOpenData

**Comment by Rubber1Duck** [comment]
Danke für die Antwort, und die Daten
