### ISSUE TITLE
Archiv vom 22.10.2024 fehlt

### ISSUE THREAD

**Issue by Rubber1Duck** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv#39]
nach dem gestrigen Ausfall fehlt noch immer das Archiv vom 22.10.2024

**Comment by Rubber1Duck** [comment]
ui ui ui , das dauert aber ........

**Comment by Rubber1Duck** [comment]
Hallo, wird es das DatenFile vom 22.10.2024 noch geben?
cu
Peter

**Comment by SimonScholler** [comment]
Hallo Peter,

ja, leider dauert das alles länger als vermutet. Wir haben intern Rückmeldung erhalten, dass die Daten vermutlich nachgeliefert werden können, aber wir warten auf weitere Rückmeldung, wann das passieren wird. Wir bleiben aber dran.
Tut mir leid für die Verzögerung.

Viele Grüße
Simon | RKI Open Data Team

**Comment by HannesWuensche** [comment]
Liebe Alle, 

wir konnten soeben die fehlende Archiv Datei hinzufügen. 

> [Archiv/2024-10-22_Deutschland_SarsCov2_Infektionen.csv.xz](https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv/blob/main/Archiv/2024-10-22_Deutschland_SarsCov2_Infektionen.csv.xz)

Mit besten Grüßen
@HannesWuensche 
für das Team | RKI Open Data

**Comment by Soran56** [comment]
Datafile of 2024-10-22 is corrupt.

xz -d 2024-10-22_Deutschland_SarsCov2_Infektionen.csv.xz
xz: 2024-10-22_Deutschland_SarsCov2_Infektionen.csv.xz: Compressed data is corrupt

Same result on Windows with error code 0x8000FFFF

**Comment by HannesWuensche** [comment]
Hallo @Soran56 ,

vielen Dank für die Hinweis. 
Der Fehler sollte behoben sein.

Mit besten Grüßen
@HannesWuensche
für das Team | RKI Open Data

**Comment by Soran56** [comment]
Es funktioniert jetzt. 
Vielen Dank für die unkomplizierte Lösung.

**Comment by Soran56** [comment]
Die Daten sind aber wertlos. Der 22.10.2024 war ein Dienstag. Also sollten neue Fälle enthalten sein. Es existieren in dem File aber keine neuen Fälle. Es werde nur neu Genesene übermittelt.

Vielleicht kann das noch jemand gegen prüfen.

**Comment by Rubber1Duck** [comment]
> Die Daten sind aber wertlos. Der 22.10.2024 war ein Dienstag. Also sollten neue Fälle enthalten sein. Es existieren in dem File aber keine neuen Fälle. Es werde nur neu Genesene übermittelt.
> 
> Vielleicht kann das noch jemand gegen prüfen.

Hallo Soran56, das kann ich NICHT bestätigen!
bundesweit in meiner Auswertung für den 22.10.2024
2991 neue Fälle und 29 neue Todesfälle

**Comment by Soran56** [comment]
Vielen Dank. Dann muss ich bei mir schauen, wo es dran liegt.

Case closed.
